'use client';

import { useState } from 'react';
import { useParams } from 'next/navigation';
import Button from '@/components/Button';
import EmptyState from '@/components/EmptyState';
import ErrorRetry from '@/components/ErrorRetry';
import PageBack from '@/components/PageBack';
import PageHeader from '@/components/PageHeader';
import SignInRequired from '@/components/SignInRequired';
import ComposerSkeleton from '@/components/forum/ComposerSkeleton';
import PostComposer from '@/components/forum/PostComposer';
import { apiErrorMessage, isNotFound, isRetryable } from '@/lib/api/errors';
import { useBackOrParent } from '@/lib/backNavigation';
import { useDocumentTitle } from '@/lib/useDocumentTitle';
import { patchListedPost, patchThreadPage } from '@/lib/forumCache';
import { sharedGroupsContent } from '@/lib/forumModel';
import { readForumPreview, rememberForumPreview } from '@/lib/forumTransition';
import { useEscapeBack, useSession } from '@/lib/hooks';
import { useResource, SKIP } from '@/lib/resource';
import { forumThread } from '@/lib/resources';

/**
 * 编辑帖子 — the author's own post, in the form it was written with (the original front end let
 * only the author edit; staff may delete, from the thread). Not in the drawer, so it has a back
 * affordance, to the thread. Saved, it goes back to the thread, which shows the edit at once:
 * the list's copy and the thread's are corrected here rather than re-read.
 */
export default function EditForumPostPage() {
  const { id } = useParams<{ id: string }>();
  const { user, token, ready } = useSession();
  const back = useBackOrParent(`/forum/${id}`);
  const [preview] = useState(() => readForumPreview(id));
  const read = useResource(forumThread, ready && token ? { id, page: 1, token } : SKIP);
  const post = read.data?.post ?? preview;
  const myId = Number(user?.id);
  const own = post !== null && Number.isSafeInteger(myId) && myId > 0 && post.user_id === myId;
  /* Escape leaves only while there is no form on screen: the form's words are saved as they
     change, but a stray key should not be what leaves an edit. */
  useEscapeBack(back, !token || !post);
  /* No layout of its own for metadata (the thread's names every route under it, and a new layout
     route would need the route types regenerated by a build). */
  useDocumentTitle('编辑帖子 - PicPony');

  let body: React.ReactNode;
  if (!ready) body = <ComposerSkeleton />;
  else if (!token) body = <SignInRequired description="登录后即可编辑自己的帖子。" />;
  else if (!post && read.error !== undefined) {
    body = isNotFound(read.error) ? (
      <EmptyState
        title="帖子不存在或已被删除"
        action={
          <Button variant="tonal" onClick={back}>
            返回
          </Button>
        }
      />
    ) : (
      <ErrorRetry
        title="帖子加载失败"
        message={apiErrorMessage(read.error)}
        onRetry={isRetryable(read.error) ? read.refresh : undefined}
      />
    );
  } else if (!post) body = <ComposerSkeleton />;
  else if (!own) body = <EmptyState title="只能编辑自己的帖子" />;
  else {
    body = (
      <PostComposer
        key={`${token}:${post.id}`}
        userId={String(myId)}
        token={token}
        post={post}
        onDone={(postId, sent) => {
          const patch = {
            title: sent.title,
            excerpt: sent.excerpt,
            category: sent.category,
            cover_image: sent.cover_image,
          };
          /* The body as the thread will read it — for a tag-group share, the document the server
             writes from the note and the groups. */
          const content =
            sent.category === 'taggroups' && sent.shared_groups
              ? sharedGroupsContent(sent.content, sent.shared_groups)
              : sent.content;
          patchListedPost(postId, { ...patch, content });
          rememberForumPreview({ ...post, ...patch, content });
          /* Corrected before the re-read: this page holds the thread's first page mounted, so
             invalidating keeps that answer on screen while it re-reads — and the thread, going
             back to it, showed the old title until the re-read landed. */
          patchThreadPage({ id, page: 1, token }, (previous) => ({
            ...previous,
            post: { ...previous.post, ...patch, content },
          }));
          forumThread.invalidate();
          back();
        }}
        onCancel={back}
      />
    );
  }

  return (
    <>
      <PageBack onClick={back} />
      <div className="mx-auto w-full max-w-4xl page-back-room">
        <PageHeader title="编辑帖子" />
        {body}
      </div>
    </>
  );
}
